[package]
name = "forwarder"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
log = "0.4.20"
socket2 = { version = "0.5.5", features = ["all"] }
mio = { version = "1.0.2", features = ["net", "os-poll"] }
parking_lot = "0.12.3"
smoltcp = { version = "0.12.0", default-features = false, features = ["proto-ipv4", "proto-ipv6"] }
libc = "0.2.158"
