[package]
name = "forwarder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
lazy_static = "1.4.0"
log = "0.4.20"
ntest = "0.9.0"
simple_logger = "4.2.0"
tokio = { version = "1.29.1", features = ["full"] }
tower = { version = "0.4.13", features = ["tokio"] }
