name: docker build & push to registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # use path context instead of git because we need git history for Vergen to work
          context: .
          push: true
          tags: ghcr.io/arian8j2/forwarder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Delete old packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: forwarder
          package-type: container
          min-versions-to-keep: 5
