name: docker build & push to registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/arian8j2/forwarder:latest
          cache-from: type=registry,ref=ghcr.io/arian8j2/forwarder:latest
          cache-to: type=inline

      - name: Delete old packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: forwarder
          package-type: container
          min-versions-to-keep: 5
