name: docker build & push to registry

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # use path context instead of git because we need git history for Vergen to work
          context: .
          push: true
          tags: ghcr.io/arian8j2/forwarder:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
